### ISSUE TITLE
multipoint slice (unbound case and modify)

### ISSUE THREAD

**Issue by anriban** [RENCI-NRIG/orca5#41] opened 2016-01-15 17:31 UTC
The request is here: http://geni-images.renci.org/images/anirban/mp-test-2.rdf , which was a 5 way multipoint slice (16 each on 4 node groups and 1 vm) that was unbound. When the slice is submitted, it seems that the set of reservations obtained are correct. For example, submission of this request gave reservations for VMs in two sites (32 in one and 33 in another) and an ion vlan. When I query for the manifest, it shows only the three active vlan reservations and only one failed VM reservation with the following error. There is no sign of the rest of the 64 VMs when I "View as a List".

/9b0d421b-80c8-46cf-8956-0eb54e31b890/MasterGroup
Failed 
Reservation 75a979d2-7f75-4fcc-bccb-bcab15ce771d (Slice ani-mp-unbound-1) is in state [Failed,None] Last ticket update: java.lang.IllegalArgumentException: Count can only be 1
No management access

**Comment by ibaldin** [comment] 2017-12-14 22:05
@hinchliff is any of this addressed by the current merge?

**Comment by hinchliff** [comment] 2017-12-18 14:31
This has not been fixed.  Running in a test environment, Orca currently returns something like this:
```
2017-12-18 09:24:01,695 [main] DEBUG controller.OrcaXmlrpcHandler-(OrcaXmlrpcHandler.java:423) - createSlice(): returning result Here are the leases: 
Request id: f29e19bc-1332-4c3c-9bd6-5a948f070fa9
[   Slice UID: f29e19bc-1332-4c3c-9bd6-5a948f070fa9 | Reservation UID: 51c9b196-335d-42ac-ab1e-819377aae862 | Resource Type: ion/vlan.vlan | Resource Units: 1 ] 
[   Slice UID: f29e19bc-1332-4c3c-9bd6-5a948f070fa9 | Reservation UID: 6fbf2f1f-2c84-4f43-9426-c4f84359f65a | Resource Type: rciNet/vlan.vlan | Resource Units: 1 ] 
[   Slice UID: f29e19bc-1332-4c3c-9bd6-5a948f070fa9 | Reservation UID: f75500a7-ea97-4fc4-98d5-46e8ff137d7a | Resource Type: nlr/vlan.vlan | Resource Units: 1 ] 
[   Slice UID: f29e19bc-1332-4c3c-9bd6-5a948f070fa9 | Reservation UID: 8b7e4a0f-5205-4f6d-9b84-0e7cb52e1c07 | Resource Type: ben/vlan.vlan | Resource Units: 1 ] 
[   Slice UID: f29e19bc-1332-4c3c-9bd6-5a948f070fa9 | Reservation UID: 3cb4f1cf-641c-4175-8750-1fe1dc2acad8 | Resource Type: rcivmsite/vm.vm | Resource Units: 32 ] 
[   Slice UID: f29e19bc-1332-4c3c-9bd6-5a948f070fa9 | Reservation UID: e24641a9-2900-4a2e-8282-f460c058b161 | Resource Type: pscvmsite/vm.vm | Resource Units: 33 ] 
[   Slice UID: f29e19bc-1332-4c3c-9bd6-5a948f070fa9 | Reservation UID: fd5f36c7-d182-4b84-8e07-d7370d94e98d | Resource Type: pscNet/vlan.vlan | Resource Units: 1 ] 
```

**Comment by hinchliff** [comment] 2017-12-19 15:25
The same exact thing happens with a single large nodegroup (64 units), connected to a broadcast link -- the large NodeGroup is split, and the resulting leases contain reservations with e.g. "Resource Units: 32".  The fact that the original request was MultiPoint and joined together doesn't seem necessary to replicate this bug.

It looks to me like the problem is that the function [generateVCConnection()](https://github.com/RENCI-NRIG/orca5/blob/orca-5.2.1/embed/src/main/java/orca/embed/cloudembed/controller/UnboundRequestHandler.java#L210) doesn't add the necessary NodeGroup information to the ComputeElements that are created by this function.

**Comment by hinchliff** [comment] 2017-12-20 14:51
I believe the [Modify portion](https://github.com/RENCI-NRIG/orca5/issues/41#issuecomment-172093576) of this ticket is a known issue, where [MultiPoint modify doesn't work because departure drive AM policy does not support it](https://github.com/RENCI-NRIG/orca5/issues/106#issuecomment-296676004).

**Closed** 2017-12-20 15:01 UTC
Labels: bug
