### ISSUE TITLE
Missing netmask property in slice description after slice modification

### ISSUE THREAD

**Issue by Bun** [RENCI-NRIG/orca5#48] opened 2016-03-15 17:54 UTC
I've added a link between two existing nodes using slice modification. I have assigned fixed IPs to the related interfaces (172.30.0.5 and 172.30.0.6) with a netmask of 255.255.255.252.

After modification, the IP addresses are present in the RDF, but the netmask is not. The relevant link is called "ModifiedLink1".
- [Modification request](https://github.com/RENCI-NRIG/orca5/files/174502/modify-request.txt)
- [Resulting RDF](https://github.com/RENCI-NRIG/orca5/files/174504/broken-netmask.txt)

**Comment by ibaldin** [comment] 2016-10-24 17:08
@YufengXin please take a look - should be an easy fix, no? Seems this has been languishing for a while.

**Comment by YufengXin** [comment] 2016-10-25 18:25
I tested it in emulator and saw the mac property was being sent:

—controller output---------
INFO   | jvm 1    | 2016/10/24 19:05:05 | Number of new parent reservations:1;num_interface=0;num_storage=0
INFO   | jvm 1    | 2016/10/24 19:05:05 | parent r_id=326910a8-e60f-440b-a834-b13ba6ed8153;unit tag:2;unit_parent_url:http://geni-orca.renci.org/owl/6c3e0b9e-2b34-4006-ae80-74abb624e451#Link0;n=10
INFO   | jvm 1    | 2016/10/24 19:05:05 | modifycommand:addiface:properties:{parent.url=http://geni-orca.renci.org/owl/6c3e0b9e-2b34-4006-ae80-74abb624e451#Link0, vlan.tag=2, hosteth=vlan-data, ip=172.16.0.1/30, mac=fe:16:3e:00:1f:07}
INFO   | jvm 1    | 2016/10/24 19:05:06 | SUCCESS ON MODIFY WATCH OF [326910a8-e60f-440b-a834-b13ba6ed8153]
INFO   | jvm 1    | 2016/10/24 19:05:06 | Number of new parent reservations:1;num_interface=0;num_storage=0
INFO   | jvm 1    | 2016/10/24 19:05:06 | parent r_id=326910a8-e60f-440b-a834-b13ba6ed8153;unit tag:2;unit_parent_url:http://geni-orca.renci.org/owl/6c3e0b9e-2b34-4006-ae80-74abb624e451#Link0;n=10
INFO   | jvm 1    | 2016/10/24 19:05:06 | modifycommand:addiface:properties:{parent.url=http://geni-orca.renci.org/owl/6c3e0b9e-2b34-4006-ae80-74abb624e451#Link0, vlan.tag=2, hosteth=vlan-data, ip=172.16.0.2/30, mac=fe:16:3e:00:62:6c}



———reservationProperty in pequad----------
	modify.subcommand.1 = modify.addiface
	modify.1.vlan.tag = 2
	modify.1.ip = 172.16.0.2/30
	modify.1.mac = fe:16:3e:00:62:6c





Yufeng Xin, PhD
RENCI
UNC at Chapel Hill
1-919-445-9633
yxin@renci.org <mailto:yxin@renci.org>

**Comment by ibaldin** [comment] 2016-10-25 18:28
I think the issue is it isn't set in the manifest.

**Comment by mcevik0** [comment] 2016-10-26 22:52
Hello Ben @Bun  ,
UVA-NL rack is updated for the fix. Can you test to check if this is working now?
Best regards,
Mert

**Comment by hinchliff** [comment] 2017-02-01 14:27
I tested this in emulation, and it looks like this is fixed.

> <rdf:Description rdf:about="http://geni-orca.renci.org/owl/9a49a872-d38e-40d3-8bb3-898d923be261#Link0-Node0/0">
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/ip4.owl#IPAddress"/>
    <j.6:label_ID>172.16.0.2/30</j.6:label_ID>
    <j.8:netmask>255.255.255.252</j.8:netmask>
  </rdf:Description>

Note: If you don't `Configure Slice` → `Auto IP` in Flukes, the manifest does not contain IP or netmask information.

**Comment by hinchliff** [comment] 2017-02-01 14:46
Actually, this one may _not_ be fixed, because a different portion of the manifest does not include the netmask, only the IP:

>  <rdf:Description rdf:about="http://geni-orca.renci.org/owl/9a49a872-d38e-40d3-8bb3-898d923be261#Link0-Node0/0/intf">
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/topology.owl#Interface"/>
    <j.6:label_ID>172.16.0.2/30</j.6:label_ID>
    <j.8:localIPAddress rdf:resource="http://geni-orca.renci.org/owl/9a49a872-d38e-40d3-8bb3-898d923be261#Link0-Node0/0"/>
    <owl:sameAs rdf:resource="http://geni-orca.renci.org/owl/9a49a872-d38e-40d3-8bb3-898d923be261#Link0-Node0"/>
    <j.8:macAddress>fe:16:3e:00:33:86</j.8:macAddress>
  </rdf:Description>

(Theory is that only the Request includes the netmask, but not the Model -- ?)

**Comment by hinchliff** [comment] 2017-02-10 18:21
I have a working fix for this committed in the branch [48_netmask](https://github.com/RENCI-NRIG/orca5/compare/48_netmask?expand=1), and there are some unit tests that I think correctly test this behavior.

The code changes I have made up to this point could use some refactoring --  I would like to reduce some duplicated code.

I have one specific question about the way properties are copied in one section of [modifySlice() at line 790](https://github.com/RENCI-NRIG/orca5/blob/orca-5.1.0/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/OrcaXmlrpcHandler.java#L790): is there a reason we are only copying a select few properties?  Would it be OK to just copy all of the properties from `config` to `modifyProperties` ?

I do see that the Property key/name is being changed, but it looks like it should be easy enough to take the substring of the `config` property name to use as the new name in `modifyProperties`.

Actually, it might be interesting that this section of code don't seem to be covered in the tests I have written.  When would that section of code be used? Only in `modifyremoved` reservations?  Should I make a new test for this? (I probably should, if I am going to start refactoring the code....)

**Closed** 2017-02-15 20:48 UTC
Labels: bug
