### ISSUE TITLE
Modify support for adding interfaces occasionally fails to pass properties, or passes duplicates.

### ISSUE THREAD

**Issue by vjorlikowski** [RENCI-NRIG/orca5#208] opened 2018-03-20 22:07 UTC
ORCA version is: orca-iaas-5.4.0_0_g0ece627-201801251206.

In /root/modify_failures_02_19_2018 (on tamu-hn), we have evidence of some modify failures that Yuanjun has been seeing; the following log entries demonstrate the failure:

INFO   | jvm 1    | 2018/02/16 05:48:16 | Ignoring interface in userdata: [interfaces]
INFO   | jvm 1    | 2018/02/16 05:48:16 | PRUTH: line = fa163e007201=up:ipv4:192.168.100.1/24
INFO   | jvm 1    | 2018/02/16 05:48:16 | processing key: fa163e007201
INFO   | jvm 1    | 2018/02/16 05:48:16 | Ignoring interface in userdata: fa163e007201
INFO   | jvm 1    | 2018/02/16 05:48:16 | PRUTH: line = fa163e001fd3=up:ipv4:192.168.100.1/24
INFO   | jvm 1    | 2018/02/16 05:48:16 | processing key: fa163e001fd3
INFO   | jvm 1    | 2018/02/16 05:48:16 | Ignoring interface in userdata: fa163e001fd3
INFO   | jvm 1    | 2018/02/16 05:48:16 | PRUTH: line = 
INFO   | jvm 1    | 2018/02/16 05:48:16 | processing key: 
INFO   | jvm 1    | 2018/02/16 05:48:16 | Ignoring interface in userdata: 
INFO   | jvm 1    | 2018/02/16 05:48:16 | PRUTH: line = fa163e006274=up:ipv4:
INFO   | jvm 1    | 2018/02/16 05:48:16 | processing key: fa163e006274
INFO   | jvm 1    | 2018/02/16 05:48:16 | Ignoring interface in userdata: fa163e006274
INFO   | jvm 1    | 2018/02/16 05:48:16 | PRUTH: line = fa163e001fd3=up:ipv4:192.168.100.1/24
INFO   | jvm 1    | 2018/02/16 05:48:16 | processing key: fa163e001fd3
INFO   | jvm 1    | 2018/02/16 05:48:16 | Ignoring interface in userdata: fa163e001fd3
INFO   | jvm 1    | 2018/02/16 05:48:16 | PRUTH: line = [storage]
INFO   | jvm 1    | 2018/02/16 05:48:16 | found section storage
INFO   | jvm 1    | 2018/02/16 05:48:16 | Adding new key to interfaces section of userdata: ${modify.3.mac}
INFO   | jvm 1    | 2018/02/16 05:48:16 | processing key: [storage]

Note that:
1) fa163e001fd3 has been submitted twice to this modify request; there is a different MAC that should have appeared here. This is one reason why Yuanjun has been seeing missing interfaces.
2) ${modify.3.mac} (a non-substituted property name) was somehow handed to the add portion of the code.

You can see the duplication mentioned in (1) in these log entries:

INFO   | jvm 1    | 2018/02/16 05:48:08 | processing key: [interfaces]
INFO   | jvm 1    | 2018/02/16 05:48:08 | Ignoring interface in userdata: [interfaces]
INFO   | jvm 1    | 2018/02/16 05:48:08 | PRUTH: line = fa163e007201=up:ipv4:192.168.100.1/24
INFO   | jvm 1    | 2018/02/16 05:48:08 | processing key: fa163e007201
INFO   | jvm 1    | 2018/02/16 05:48:08 | Ignoring interface in userdata: fa163e007201
INFO   | jvm 1    | 2018/02/16 05:48:08 | PRUTH: line = fa163e001fd3=up:ipv4
INFO   | jvm 1    | 2018/02/16 05:48:08 | processing key: fa163e001fd3
INFO   | jvm 1    | 2018/02/16 05:48:08 | Modifying interface ing userdata: fa163e001fd3
INFO   | jvm 1    | 2018/02/16 05:48:08 | PRUTH: line = fa163e006274=up:ipv4:
INFO   | jvm 1    | 2018/02/16 05:48:08 | processing key: fa163e006274
INFO   | jvm 1    | 2018/02/16 05:48:08 | Ignoring interface in userdata: fa163e006274
INFO   | jvm 1    | 2018/02/16 05:48:08 | PRUTH: line = [storage]
INFO   | jvm 1    | 2018/02/16 05:48:08 | found section storage
INFO   | jvm 1    | 2018/02/16 05:48:08 | Adding new key to interfaces section of userdata: fa163e001fd3

The duplication causes the python code that interfaces to libvirt to fail, when trying to add an interface with a MAC address that's already present in the VM, as shown here:

INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] [interfaces]
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] fa163e007201=up:ipv4:192.168.100.1/24
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] fa163e001fd3=up:ipv4
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] fa163e006274=up:ipv4:
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] [storage]
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] [routes]
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] [scripts]
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] bootscript=apt-get update
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo]   apt-get -y install openvswitch-switch
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo]    apt-get -y install iperf
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo]    /etc/init.d/neuca stop
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo]   
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] 
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] 
INFO   | jvm 1    | 2018/02/16 05:48:05 |      [echo] 
INFO   | jvm 1    | 2018/02/16 05:48:08 |      [exec] Result: 1
INFO   | jvm 1    | 2018/02/16 05:48:08 |      [echo] result code: 1
INFO   | jvm 1    | 2018/02/16 05:48:08 |      [echo] output: 
INFO   | jvm 1    | 2018/02/16 05:48:08 |      [echo] About to update userdata file: 
INFO   | jvm 1    | 2018/02/16 05:48:08 |      [echo] mac        :  fa:16:3e:00:1f:d3
INFO   | jvm 1    | 2018/02/16 05:48:08 |      [echo] state      :  up
INFO   | jvm 1    | 2018/02/16 05:48:08 |      [echo] ipversion  :  ipv4
INFO   | jvm 1    | 2018/02/16 05:48:08 |      [echo] ip         :  192.168.100.1/24

The "result code: 1" is the python handler code returning an error, but the handler does not fail.
Subsequent issue to be filed regarding the handler script error exit, and the failure of the handler to catch it.

Similarly, with case (2), the unexpanded property is being handed to the handler, and the downstream python code, which *also* results in errors; see:

INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] [interfaces]
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] fa163e007201=up:ipv4:192.168.100.1/24
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] fa163e001fd3=up:ipv4:192.168.100.1/24
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] 
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] fa163e006274=up:ipv4:
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] fa163e001fd3=up:ipv4:192.168.100.1/24
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] [storage]
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] [routes]
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] [scripts]
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] bootscript=apt-get update
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo]   apt-get -y install openvswitch-switch
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo]    apt-get -y install iperf
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo]    /etc/init.d/neuca stop
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo]   
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] 
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] 
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] 
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] 
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [exec] Result: 1
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] result code: 1
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] output: 
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] About to update userdata file: 
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] mac        :  ${modify.3.mac}
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] state      :  up
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] ipversion  :  ipv4
INFO   | jvm 1    | 2018/02/16 05:48:16 |      [echo] ip         :  

Note that the handler is echoing back "${modify.3.mac}" as the MAC to have been added (which obviously failed).

Thus - this issue is about generalized modify property handling; there's two problems that encapsulates:
1) The wrong property is being handed down (which means an already handled MAC may be handed down in place of a newly generated one) to the handler.
2) Unexpanded properties are being handed down to the handler.

**Comment by ibaldin** [comment] 2018-03-20 22:20
From Yanjun:
```
Hi Ilya,

For the simplest possible scenario, it is easy to repeat on flukes. 
1. Create a slice with only one node running Ubuntu 14.04, wait for it to become active. 
2. Then add a broadcast link, and connect the broadcast link with the node. Wait for the link to become active. Now there are "eth0" and "eth1" on the node if you check it with "ifconfig -a".
3. Add another broadcast link, and connect it to the node. Wait for the link to become active. Now there should be "eth0", "eth1" and "eth2" on the node, but "eth2" is missing.
I have tried this on FIU and UMASS, hopefully this is the same for others. If you cannot repeat it or you think it necessary to have a Ahab program for repeating this automatically, please let me know.

```

**Comment by ibaldin** [comment] 2018-03-20 22:21
Also from Yuanjun (AHAB-based):
```
Hi all,

To repeat the failure that ExoGENI doesn't create a new interface for new links, I created a new branch called debug at RENCI-NRIG/SAFE project. You can access it with "git clone -b debug https://github.com/RENCI-NRIG/SAFE.git".

The dependencies of the code are jdk8 and ahab-0.1.7 (should be manually installed to local repository). The dependencies.sh under SAFE directory might help if you are running Ubuntu. I haven't figured out how to modify pom file to use local dependencies yet. It worked on my desktop, but when I tried on a Ubuntu VM on ExoGENI, maven failed to find the ahab libraries. 

To run the code, first modify SAFE/configure to set the location of your ssh key and ExoGENI pem file. You may also modify other fields to change the name of the slices and the sites to test on. Enter SAFE directory and run "./configure", this should adapt the configuration files in SAFE/SDX-Simple/config/ and SAFE/SDX-Simple/client-config/, so you don't need to touch them. 
Second, enter SAFE/SDX-Simple  directory, run "./scripts/build.sh" to build the code.
Last, run "./scripts/test.sh" to run the test program.

The test program will create a sdx slice with routers and bro nodes on two sites, and we have 4 customer slices, with two on each site. We stitch the customer slices to the sdx slice. After the program finishes, there should be 6 interfaces on c0 and 5 on c1 (including management interface eth0). During my tests, c1 node on FIU site always has only 4 interfaces. 
```

**Comment by vjorlikowski** [comment] 2018-03-21 02:58
Adding text of email from me to Yuanjun to ticket:

Yuanjun:

Do you have 4 dataplane interfaces on the VMs you modify?
Is one of those, the second, modified after you've added a previous
interface?

Reason I ask...

Look at this block of logs:

INFO | jvm 1 | 2018/02/16 05:48:08 | processing key: [interfaces]
INFO | jvm 1 | 2018/02/16 05:48:08 | Ignoring interface in userdata: [interfaces]
INFO | jvm 1 | 2018/02/16 05:48:08 | PRUTH: line = fa163e007201=up:ipv4:192.168.100.1/24
INFO | jvm 1 | 2018/02/16 05:48:08 | processing key: fa163e007201
INFO | jvm 1 | 2018/02/16 05:48:08 | Ignoring interface in userdata: fa163e007201
INFO | jvm 1 | 2018/02/16 05:48:08 | PRUTH: line = fa163e001fd3=up:ipv4
INFO | jvm 1 | 2018/02/16 05:48:08 | processing key: fa163e001fd3
INFO | jvm 1 | 2018/02/16 05:48:08 | Modifying interface ing userdata: fa163e001fd3
INFO | jvm 1 | 2018/02/16 05:48:08 | PRUTH: line = fa163e006274=up:ipv4:
INFO | jvm 1 | 2018/02/16 05:48:08 | processing key: fa163e006274
INFO | jvm 1 | 2018/02/16 05:48:08 | Ignoring interface in userdata: fa163e006274
INFO | jvm 1 | 2018/02/16 05:48:08 | PRUTH: line = [storage]
INFO | jvm 1 | 2018/02/16 05:48:08 | found section storage
INFO | jvm 1 | 2018/02/16 05:48:08 | Adding new key to interfaces section of userdata: fa163e001fd3

Paul's typo in the code ("interface ing userdata") gives away that
there's a different code path being followed for the already present
MAC: fa163e001fd3

Now - one of two things is happening here:
1) You modified the interface associated with MAC: fa163e001fd3
2) ORCA somehow sent MAC fa163e001fd3 to the handler a second time,
when it shouldn't have.

I'm inclined to believe it's (1).

If I'm right, then part of what's going wrong is the addition of a
second stanza to the userdata for the MAC in question (fa163e001fd3)
- which causes all kinds of issues.

The other parts of what's going wrong, in that instance, are:
1) The interface update python code is trying to re-add an interface
that's already present, on a modification of the interface.
2) The indexing code for which interface is being selected, in the
handler, gets mucked up - resulting in what appears to be invalid
properties being passed.

We'll leave aside the fact that the handler is treating the
"[interfaces]" section header as though it's an interface, when it
does the parsing of the userdata.

If I'm right, and the pre-existing interface is "merely" being
modified, then this may all be resolved by fixing the parsing of the
userdata, fixing the codepath that accidentally re-adds the modified
interface to the userdata, ensuring we don't try to re-add
interfaces that are already present, and improving the error
handling for cases where adding or deleting an interface fails.

So - what I need confirmation on...

Is the sequence of events in your requests:
1) Add fa163e007201
2) Add fa163e001fd3
3) Add fa163e006274
4) Modify fa163e001fd3 (same MAC as in (2))
5) Add ???? (MAC unknown, due to errors in code)

**Comment by vjorlikowski** [comment] 2018-03-21 03:01
To be correct - the typo wasn't the only difference on that line... ;)

**Comment by ibaldin** [comment] 2018-03-26 16:40
Yuanjun confirms this is a problem in INTRA-rack requests. So single rack tests should show this. 

There is a question whether the fixes in https://github.com/RENCI-NRIG/orca5/releases/tag/orca-5.4.1 related to property passing fix this problem already. 

@mcevik0 will test in a limited deployment.

**Comment by mcevik0** [comment] 2018-03-26 18:20
I deployed 5.4.1 to INNO and PSC racks. Missing interface problem is not fixed. I see output matching with Victor's statements above in the very first comment (ie. Result code:1) on both racks. @ibaldin

**Comment by mcevik0** [comment] 2018-03-28 21:06
neuca-user-data from one of the failed attempts:

```
[global]
actor_id=5c51c6a1-cee5-40f8-8978-0b86c57c77fd
slice_id=f1afa1bc-1509-4105-bd74-ae1192793ae9
reservation_id=5a5b445e-9778-4174-9805-76b4e9c1d784
unit_id=5855a49a-fb63-4589-8053-bd2840efddef
;router= Not Specified
;iscsi_initiator_iqn= Not Specified
slice_name=psc-1
unit_url=http://geni-orca.renci.org/owl/e056516a-253a-4906-8385-a1f774a0143a#Node0
host_name=Node0
management_ip=147.72.248.6
physical_host=psc-w7
nova_id=9a74d160-0940-4935-ac19-3db78cf3a044


[users]
root=no:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC39cS8Fnaq8qlFWeK0SB+16GL2E5IG/yMjkKRn6eado1cFUJSWHcdyIYhNtoMQCXjMGGF3d9JJgDH3xjhGQGsuE19z6PFp4NyaqjRQzteCksj2bSP0U46e5ioh2yDLRZKqvyyGfymLqoGgHEMBM4P61D2EAgyTcxF/bF9klNC9mDyb2O62QHwlVMSQQGbkzyvw+pBpHv3X+iI6Y4xx11j47Mjf+84oHiauIW1UXbcHTjdn25bOxOpCG9cHdagswZ2R1uu1h/8s992r1Ytuqabp5aI1IJPEdfrWKGqYPzB7VQcoIXi6c7KH4JMlaYfo8rLx9388AuvAG+P+8jRHMw3b mcevik:
mcevik=yes:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC39cS8Fnaq8qlFWeK0SB+16GL2E5IG/yMjkKRn6eado1cFUJSWHcdyIYhNtoMQCXjMGGF3d9JJgDH3xjhGQGsuE19z6PFp4NyaqjRQzteCksj2bSP0U46e5ioh2yDLRZKqvyyGfymLqoGgHEMBM4P61D2EAgyTcxF/bF9klNC9mDyb2O62QHwlVMSQQGbkzyvw+pBpHv3X+iI6Y4xx11j47Mjf+84oHiauIW1UXbcHTjdn25bOxOpCG9cHdagswZ2R1uu1h/8s992r1Ytuqabp5aI1IJPEdfrWKGqYPzB7VQcoIXi6c7KH4JMlaYfo8rLx9388AuvAG+P+8jRHMw3b mcevik:


[interfaces]
fa163e006faa=up:ipv4:

fa163e006faa=up:ipv4:
[storage]
[routes]
[scripts]
```

**Comment by ibaldin** [comment] 2018-03-28 21:10
Having trouble repeating it on ExoSM. Need more time to test. I did repeat it on PSC controller.

**Comment by kthare10** [comment] 2018-04-30 17:47
**Description and Root Cause for the issue**
OrcaXmlRpcHandler::modifySlice invokes ReservationConverter::modifyReservations to construct local properties of the reservations. This function is invoked for the parent reservation i.e. VM node reservation.  OrcaXmlRpcHandler::modifySlice then adds status watchdog for all the reservations.

Successful completion of the reservation triggers ReservationDependencyStatusUpdate::success callback function. This call back uses the local properties to construct the Modify commands which are sent to the AM and then to handler.

Local Properties for one interface are overwritten and are not available. Since, any one of the interface properties can be overwritten, the problem is random. If properties are overwritten for an interface which has not been added, no modify command will be sent to AM and handler.

**Reason for overwritten local properties is because of the following code bug.**
ReservationConverter::modifyReservations generates the local properties by invoking ReservationConverter::formInterfaceProperties. modifyReservations controls the interface name using a local property ReservationConverter.PropertyParentNumInterface which is set in the VM Node Reservation object at the end of ReservationDependencyStatusUpdate::success. modifyReservations assumes that the same VM Node Reservation object is used to construct the Interface properties. This assumption is incorrect. The VM Node Reservation is fetched afresh from SM instead of using the old object. The fresh fetched Reservation does not have ReservationConverter.PropertyParentNumInterface property set. This causes the interface counter for the newly added interfaces to start for eth1 even if eth1 already exists thus overwriting properties for previously stored eth1 data.

**Possible fix**
Recompute the existing number of interfaces before processing the new interfaces in ReservationConverter::modifyReservations

**Comment by mjstealey** [comment] 2018-05-14 20:51
PR #211 merged and release published.
closing.

**Comment by kthare10** [comment] 2018-06-22 15:29
All config properties without a modify prefix are loaded into local properties. Any update to local properties is saved as modify.x.<propertyname> config property as a result of modifySlice
Example:
For a VM created with two interfaces unit.number.interface is set to 2 in config properties
On receipt of a modify to add an interface to the VM this unit.number.interface is loaded into localProperties too. So at the beginning of the modify; unit.number.interface(local) and unit.number.interface(config) are both 2
After modify is successful; the code updates unit.number.interface(local) to 3 and sends it to update
unit.number.interface(local) is saved as modify.x.unit.number.interface in config properties. At this point unit.number.interface is still 2. On subsequent modify unit.number.interface(local) is filled with value from unit.number.interface(config) i.e. 2 and modify.x.unit.number.interface = 3; 

Initial fix checked if unit.number.interface existed in local; it used that and check config properties only in case of unavailability of config value. Code should always use modify.x.unit.number.interface if present; otherwise use unit.number.interface. The above approach works fine; but AUT framework does not work on config properties and requires local properties. In order for AUT framework to continue to work, a check is added to use higher of the local or config property value for unit.number.interface

**Closed** 2018-07-05 17:17 UTC
